env:
  browser: true
  es6: true
extends: eslint:recommended
parserOptions:
  sourceType: module
  ecmaVersion: 9
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator:
        var: 2
        let: 2
        const: 3
  linebreak-style:
    - error
    - unix
  no-multi-spaces:
    - error
    - exceptions:
        SwitchCase: true
  no-unused-vars:
    - error
    - args: all
      argsIgnorePattern: "^_"
      ignoreRestSiblings: true
      caughtErrors: all
      caughtErrorsIgnorePattern: "^_"
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - never
